### PR TITLE
feat(5): add nextjs skeleton app

### LINKED ISSUE #5: Create a skeleton app in NextJS
We want to use nextjs

### PR DESCRIPTION
**Pull request by TheJoin95**
Closes #5

### CODE REVIEW

**Review by 404answernotfound — COMMENTED** [review]
looks good, i'll find some time in the evening to work on responsiveness and we can merge. If someone wants to pick it up before then you are welcome to! 🍡

**Comment by TheJoin95** [comment]
Good. In the afternoon I'm going to add couple of issues for the navbar pages, footer, and so on.

Do we need an user login page? I believe not, if so we should remove the user profile icon on navbar right side

**Comment by 404answernotfound** [comment]
> Good. In the afternoon I'm going to add couple of issues for the navbar pages, footer, and so on.
> 
> Do we need an user login page? I believe not, if so we should remove the user profile icon on navbar right side

I thought it would be "funny" to have Erwin Schrodinger's picture as the main user of the page, without actually having any logins whatsoever.

Yay or nay?

**Comment by TheJoin95** [comment]
Yay.

I see you. Ok, in that case I agree it would be great but we need to add something more. Maybe the image would be a gif or a css animation so the user will click on it. We should add a label or a hidden Easter egg on it.

I'll open a issue on this but, yay, great idea!

**Pull request merged**
