### PR TITLE
added lavorio digitale italia as diamond sponsor

### PR DESCRIPTION
**Pull request by pewpewnor**
Added image component as link to "https://lavorodigitaleitalia.it/" in file _components/SponsorTable.tsx_
Added _lavorio-digitale-italia_logo.svg_ into _/public_
#204

### CODE REVIEW

**Review by TheJoin95 — COMMENTED** [review]
Hi, thanks for the PR.

I think we should use a negative version of the log and a smaller one.
@nicpuppa @404answernotfound could it be possible? thanks

**Comment by nicpuppa** [comment]
@TheJoin95 this is the logo that they give to us. 
Maybe we can try to remove the bottom part of the logo and leave only "LAVORO DIGITALE ITALIA", what do you think ?

**Comment by TheJoin95** [comment]
If it's not mandatory to them, yes, it would be great.  @pewpewnor could you edit the svg?

**Comment by nicpuppa** [comment]
In their website the logo is just the full name, so I suppose it is ok

**Review by TheJoin95 — APPROVED** [review]

**Review by nicpuppa — CHANGES_REQUESTED** [review]
@pewpewnor can you try with width=200 and height=150 ?

**Comment by pewpewnor** [comment]
> @pewpewnor can you try with width=200 and height=150 ?

got it

**Review by nicpuppa — APPROVED** [review]
Much better now, thank you again @pewpewnor

**Pull request merged**
