### PR TITLE
feat(291): update seo for 2024 edition

### LINKED ISSUE #291: Update SEO on LP for 2024 osday

### PR DESCRIPTION
**Pull request by TheJoin95**
Closes #291

### CODE REVIEW

**Comment by Wabri** [comment]
Maybe also the footer need to be updated
https://github.com/Schrodinger-Hat/osday/blob/5d165d71bb924fd84e4aadd86c92065ebdf14be0/components/Footer.tsx#L58

**Comment by TheJoin95** [comment]
Nope, have a look on the preview. The copyright should be for the current year

**Review by Wabri — DISMISSED** [review]

**Review by Readpato — APPROVED** [review]
Fixed a little typo. Everything else looks good =]

**Comment by TheJoin95** [comment]
Approvals, merging

**Pull request merged**
