### PR TITLE
Add sponsor logos

### LINKED ISSUE #74: Add jetbrains, github, gitkraken logos to sponsor page
Here is the logos:
https://www.jetbrains.com/company/brand/logos/
https://github.com/logos
https://www.gitkraken.com/store (end of page)

### PR DESCRIPTION
**Pull request by AngyDev**
Add logos to sponsor page 
Close #74 #85

### CODE REVIEW

**Review by 404answernotfound — COMMENTED** [review]
Nice job Angy, just one quick question for everyone: do we want to generalise the "Sponsored by" phrase as is now or would we rather split sponsors based on the glossary we already have?

Platinum, Diamond, Gold, Silver, Community, Brand, Swag...

**Comment by nicpuppa** [comment]
@404answernotfound we need to specify the category of each company. For this specific case these companies are our Swag Partner (@Wabri definition)

**Comment by Wabri** [comment]
Sorry @AngyDev I've not specify the sponsor tiers 😄

**Comment by AngyDev** [comment]
Added Nephilia Logo and divided sponsors

**Review by nicpuppa — APPROVED** [review]

**Pull request merged**
