### PR TITLE
feat: add logo Italia Open-Source

### PR DESCRIPTION
**Pull request by FabrizioCafolla**

### CODE REVIEW

**Review by Wabri — CHANGES_REQUESTED** [review]
Need to add a new element inside this div: https://github.com/Schrodinger-Hat/osday/blob/b61e5fba99629918158b889e5e20fea3632b7e96/components/SponsorTable.tsx#L120

**Comment by Wabri** [comment]
@TheJoin95 netlify needs your approval

**Comment by TheJoin95** [comment]
@Wabri anyone with the Netlify's Schrodinger account can approve

**Comment by Wabri** [comment]
Mh ok, if you say so, I try to log with sh account, but got invalid credential. Maybe I lost them 😅

**Comment by TheJoin95** [comment]
> Mh ok, if you say so, I try to log with sh account, but got invalid credential. Maybe I lost them 😅

I approved the build. Mr. president, you can't lose the credentials

**Review by TheJoin95 — APPROVED** [review]
LGTM

**Review by Wabri — APPROVED** [review]

**Pull request merged**
