### PR TITLE
Started i18n

### PR DESCRIPTION
**Pull request by 404answernotfound**

### CODE REVIEW

**Comment by TheJoin95** [comment]
We want to use react-intl, am I right?

**Comment by 404answernotfound** [comment]
> We want to use react-intl, am I right?

You should already find all the packages installed!

There a t hook and the package name is i18next with react

**Comment by TheJoin95** [comment]
Oki, you can go ahead on configuring it. You should rebase

**Comment by TheJoin95** [comment]
Please, add the `fr` locale

**Review by TheJoin95 — APPROVED** [review]

**Pull request merged**
