### PR TITLE
feat(SponsorTable): add suse sponsorship

### LINKED ISSUE #459: Add Suse as Platinum
[www.suse.com](http://www.suse.com/)

SUSE

### PR DESCRIPTION
**Pull request by Wabri**
Closes #459

### CODE REVIEW

**Review by TheJoin95 — COMMENTED** [review]
VERY NICE, non si legge

**Comment by TheJoin95** [comment]
Do we have a negative logo version ? Otherwise let's go with this one

**Review by TheJoin95 — APPROVED** [review]
It's good now

**Comment by Wabri** [comment]
Let me try the other logos, than I'll merge with a single commit

**Comment by Wabri** [comment]
Ok i guess 😂

**Comment by TheJoin95** [comment]
White it's the one

**Pull request merged**
