### PR TITLE
Feat: Edition dropdown

### PR DESCRIPTION
**Pull request by Readpato**
Addresses https://github.com/Schroedinger-Hat/schroedinger-hat/issues/304

### CODE REVIEW

**Comment by TheJoin95** [comment]
Did you check also the mobile version?

**Comment by Readpato** [comment]
Yup, mobile version is also addressed in the PR

I decided against going for a dropdown in the menu, so I just added a sub category to the "Editions" title

EDIT: **Updated the style, look at comment blow**


image

**Comment by Readpato** [comment]
Addressed again the mobile styles since they were bothering me

image

**Comment by TheJoin95** [comment]
From desktop the link is working only if I click on the text and not if I'm clicking on the box

**Comment by TheJoin95** [comment]
^^ Same in mobile

**Comment by Readpato** [comment]
Good catch @TheJoin95, fixed it :)

**Review by TheJoin95 — APPROVED** [review]

**Pull request merged**
