### PR TITLE
ADD new swag sponsor added to sponsorTable

### LINKED ISSUE #223: Add treedom as Swag Partner
01_Green_logo (1)

Link: https://www.treedom.net/

### PR DESCRIPTION
**Pull request by rennavittorio**

### CODE REVIEW

**Comment by nicpuppa** [comment]
Hi @rennavittorio, congrats for your first contribution! 🥳

Can you please provide a screenshot of the new sponsor table ?

**Comment by rennavittorio** [comment]
> 

hi @nicpuppa ! nice to meet you! Here is the screen related to issue 223
screen-issue-223

**Review by nicpuppa — APPROVED** [review]

**Comment by nicpuppa** [comment]
Thanks @rennavittorio, well done!

**Review by davideimola — APPROVED** [review]
Good work @rennavittorio. LGTM

**Pull request merged**
