### PR TITLE
feat: add sticky header with transition

### LINKED ISSUE #10: Add sticky header or change CSS

### PR DESCRIPTION
**Pull request by TheJoin95**
Closes #10

### CODE REVIEW

**Review by nicpuppa — APPROVED** [review]

**Review by Wabri — APPROVED** [review]

**Review by 404answernotfound — CHANGES_REQUESTED** [review]
Riusciamo a farla leggermente più lenta la transizione?

**Comment by 404answernotfound** [comment]
Can you guys check the changes that I made? @TheJoin95

**Review by nicpuppa — CHANGES_REQUESTED** [review]
The notification menu seems broken when you scroll down.

**Comment by 404answernotfound** [comment]
> The notification menu seems broken when you scroll down.

thanks for the heads up! check again!

**Review by nicpuppa — APPROVED** [review]
Good job

**Review by 404answernotfound — APPROVED** [review]

**Review by davideimola — APPROVED** [review]

**Pull request merged**
