### PR TITLE
adding the day (24) to dates displayed

### PR DESCRIPTION
**Pull request by rvailleux**
added the day to dates + some improvement on the french description.

### CODE REVIEW

**Review by Wabri — APPROVED** [review]
Thank you very much 🥇

**Comment by 404answernotfound** [comment]
We will merge after the date is confirmed, tomorrow :)

**Comment by nicpuppa** [comment]
@rvailleux can you rebase the branch please ? Thank you!

**Review by 404answernotfound — APPROVED** [review]

**Comment by 404answernotfound** [comment]
can we merge this? :) @TheJoin95  @Wabri  @nicpuppa

**Comment by TheJoin95** [comment]
Merci pour les corrections en français, je suis encore novice dans la langue !

Two approvals, merged.

**Comment by rvailleux** [comment]
@TheJoin95 No worries, happy to review and improve anytime.

**Pull request merged**
