### PR TITLE
Started working on sponsorship table

### LINKED ISSUE #57: sponsor page
https://2023.osday.dev/sponsor#

The links to the sponsor tiers to 'know more' do not work. Is this on purpose or bug? Thanks!

### LINKED ISSUE #70: Sponsor page restyling

### PR DESCRIPTION
**Pull request by 404answernotfound**
Closes #57 
Closes #70

### CODE REVIEW

**Comment by TheJoin95** [comment]
Please rebase

**Comment by nicpuppa** [comment]
@404answernotfound only for desktop, if we put the tiers as rows and offers as colums we can have more content  horyzontally. For now I like this solution only for mobile

**Comment by davideimola** [comment]
Perhaps @nicpuppa is right! I didn't see any problem to center it on the page, as we already have some centered content (sponsors).

**Comment by TheJoin95** [comment]
@404answernotfound any updates on this?

**Comment by TheJoin95** [comment]
@404answernotfound it's looking good to me, just a note: on the platinum why we don't have the attendance list?

**Comment by nicpuppa** [comment]
@404answernotfound on mobile I see tiers only from silver to diamond, and not community and media. And also the table is not centered, right ? Can you try to center it ?

**Comment by 404answernotfound** [comment]
> @404answernotfound on mobile I see tiers only from silver to diamond, and not community and media. And also the table is not centered, right ? Can you try to center it ?

On mobile I think it's better if we leave community and brand sponsorship as boxes (which can be found at the end of the table) for positioning and width

**Comment by 404answernotfound** [comment]
> @404answernotfound it's looking good to me, just a note: on the platinum why we don't have the attendance list?

now should be alright with all real values

**Comment by 404answernotfound** [comment]
> @404answernotfound on mobile I see tiers only from silver to diamond, and not community and media. And also the table is not centered, right ? Can you try to center it ?

it's set to be at the same margin as the header, hero, footer. Do you want to center it?

**Comment by nicpuppa** [comment]
@404answernotfound good to me! Well done

**Comment by 404answernotfound** [comment]
> @404answernotfound good to me! Well done. But you need to review the values

which ones? I thought I did them correctly now lol

**Comment by 404answernotfound** [comment]
@nicpuppa @TheJoin95 @Wabri @davideimola values were reviewed, can you approve this PR?

**Review by TheJoin95 — APPROVED** [review]
Good job!

**Pull request merged**
