### PR TITLE
sponsorship table

### PR DESCRIPTION
**Pull request by 404answernotfound**

### CODE REVIEW

**Comment by TheJoin95** [comment]
We should remove the old sponsors components from the sponsor page "footer", we could comment that part of the code

**Comment by TheJoin95** [comment]
I'd say: let's add a quick link to download / view the sponsorship pdf as well

**Comment by TheJoin95** [comment]
`Call for sponsors will be open until 1st of March 2024`

Can we end it on the 17th Feb ?

**Comment by 404answernotfound** [comment]
Yes to first 2 points, I'd rather keep it wider until 1st of March for this one

**Review by TheJoin95 — APPROVED** [review]

**Pull request merged**
