### PR TITLE
fix: closes #86, add offset as height of sticky header

### LINKED ISSUE #86: scroll event on dei page is broken
https://user-images.githubusercontent.com/12409541/204595184-62177851-0003-4d60-ba51-3df1970a7809.mov

### PR DESCRIPTION
**Pull request by TheJoin95**
Closes #86

### CODE REVIEW

**Comment by TheJoin95** [comment]
Add content to fix in the common resolution. This page should have more content or impaginate it in a differ way (e.g. no container).

The issue is caused by a different height of the header menu and the fixed props value

**Review by Wabri — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/12409541/205593294-a4931dd4-c959-4e05-9b9b-f988faa79211.mov

I dont know why, but the problem is still here!

**Comment by TheJoin95** [comment]
I'm gonna change the page layout

**Comment by TheJoin95** [comment]
Francamente non si risolve, è l'header che ha un'altezza diversa e che genera sto sfarfallio

**Pull request closed without merging**
