### PR TITLE
Add cfp counters

### LINKED ISSUE #124: Add cfp counters

### PR DESCRIPTION
**Pull request by Wabri**
Closes #124

### CODE REVIEW

**Comment by TheJoin95** [comment]
It seems a very nice work

**Comment by Wabri** [comment]
But is a empty pr 🤣

**Comment by davideimola** [comment]
> But is a empty pr 🤣

It is ready for production! :trollface:

**Comment by TheJoin95** [comment]
Can we close this or do you want to finish it?

**Pull request closed without merging**
